
PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = TRUE
DEBUG      = FALSE

DIM        = 2

MAX_SPEC   = 8

COMP	   = gnu

USE_MPI    = TRUE
USE_OMP    = FALSE
USE_CUDA   = FALSE

USE_PARTICLES = FALSE

Bpack   := ./Make.package
Blocs   := .

include Make.Adv
