#line 2 "BLProfParser.lex.yy.cpp"

#line 4 "BLProfParser.lex.yy.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 98
#define YY_END_OF_BUFFER 99
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[599] =
    {   0,
        0,    0,   99,   97,    1,   86,   97,   63,   97,   97,
       35,   36,   87,   93,   88,   97,   97,   50,   90,   89,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   91,   92,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,    0,    0,   50,    0,   63,   63,
        0,    0,   96,   51,    4,   51,    0,   94,   94,   94,
       94,    5,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,

       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   37,    0,   95,   51,
       51,    0,    4,    4,    0,    0,   52,   94,   94,   94,
       94,   94,   94,    2,   94,   94,   94,    3,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   64,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   29,
       94,   94,   94,   94,   94,   94,   94,   94,   94,    0,
        0,    0,   51,    0,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,    0,   53,   54,

       94,   94,   26,   94,   94,   94,   94,   66,   94,   94,
       94,   94,   94,   94,   94,   94,   44,   27,   94,   33,
       94,   85,   94,   94,   94,   94,   94,   65,   94,   62,
       94,   94,   94,   94,    0,    0,   94,   94,   94,   94,
       94,   94,   57,   94,   94,   94,   94,   94,   94,   94,
        0,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       59,   94,   94,   41,   58,   34,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   62,   94,   94,    0,
       94,   94,   94,    0,   94,   94,   94,   94,   94,   94,
       94,   94,   12,   94,   55,   94,   94,    0,   94,   94,

       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,    0,   94,   94,   94,    0,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,    0,   94,
       94,   94,   94,   94,   94,   69,   67,   94,   19,   94,
       94,   94,   94,   94,   94,    7,   94,   25,   20,   94,
       94,   94,    0,   70,   71,   72,    0,   94,   94,   94,
       94,   94,   94,   94,   16,   94,   94,   17,   94,   61,
       94,   94,   94,   94,   94,   94,   94,   24,   94,   94,
       94,   94,   94,   94,   94,   32,   94,   94,    0,    0,

       94,   94,   94,   94,   94,   94,   94,   94,   14,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   31,    0,    0,    8,
       94,   94,   94,   94,   94,   94,   94,   21,   18,   42,
       94,   94,   94,   94,   94,   94,   94,   94,   23,   94,
       94,   94,   94,   94,   94,   30,   56,   60,   94,   94,
       94,   94,   94,   94,   15,   94,   94,    0,   94,   94,
        9,   94,   10,   45,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   22,   94,   94,   94,   94,    0,
       94,   94,   68,   28,   94,   94,   94,   81,   94,   94,

       94,    6,   43,   94,   94,   13,   94,   94,    0,    0,
       94,   94,   94,   94,   73,   94,   94,   94,   94,   94,
       46,   94,    0,    0,   94,   94,   94,   94,   94,   94,
       84,   94,   94,   94,   11,   47,    0,    0,   94,   94,
       94,   94,   94,   82,   94,   94,    0,   40,    0,    0,
       94,   94,   38,   39,   94,   94,   94,    0,    0,    0,
       48,   49,   94,   94,    0,    0,    0,   79,   80,   94,
       74,    0,    0,    0,   94,    0,    0,    0,    0,   94,
        0,    0,    0,    0,   83,    0,   75,    0,    0,    0,
        0,    0,   76,    0,    0,   78,   77,    0

    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    7,    1,    8,    9,
       10,    1,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,    1,    1,
       18,    1,    1,    1,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   28,   29,   30,   31,   32,   33,
       28,   34,   35,   36,   28,   37,   28,   28,   28,   28,
       38,   28,   39,   28,   40,   28,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   28,   50,   51,   52,   53,
       54,   55,   28,   56,   57,   58,   59,   60,   61,   62,
       63,   64,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[66] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1
    } ;

static yyconst flex_uint16_t yy_base[603] =
    {   0,
        0,    0,  683,  684,   64,  684,    0,  676,  677,  615,
      684,  684,   65,  684,   68,   57,  664,   60,  684,  684,
        0,  649,   34,  641,  627,  630,  629,   44,   54,  643,
      616,   66,  635,  643,    0,    0,  629,  617,   59,   52,
      626,  635,  609,  611,   78,  619,   44,  617,   50,   53,
      612,  620,  619,  618,  113,  641,  108,  651,    0,  649,
      600,  645,  638,  116,  636,  124,  132,    0,  617,  598,
      596,    0,  594,  605,  585,  617,  581,  583,  585,  607,
      585,  613,   57,  584,  613,  605,  607,  582,  573,  591,
       91,  579,  577,  569,  569,  585,  576,  580,  569,  587,

       57,  569,  558,  568,  578,  593,  562,  571,   85,  560,
      566,  560,  553,  567,  566,  565,  602,  560,  684,  142,
      147,  155,    0,  590,  170,  148,  588,  547,  551,  549,
      555,  555,  553,    0,  568,  538,  541,    0,  552,  559,
      558,  542,  586,  556,  565,  534,  532,  533,   53,  118,
      539,  540,  531,  526,    0,  539,  527,  534,  532,  524,
      540,  527,  532,  527,  513,  519,  528,  537,  524,    0,
      516,  505,  506,  529,  517,  513,  506,  505,  504,  553,
      178,  174,  540,  191,  501,  519,  121,  496,  507,  500,
      505,  525,  505,  525,  519,  504,  490,  485,    0,    0,

      499,  498,    0,  119,  484,  129,  486,    0,  515,  480,
      477,  489,  489,  476,  470,  479,    0,    0,  487,  493,
      488,    0,  476,  485,  480,  469,  474,    0,  481,  145,
      517,  466,  465,  464,  473,  194,  470,  457,  458,  455,
      454,  455,    0,  450,  460,  451,  453,  484,  447,  451,
      454,  451,  461,  449,  447,  444,  443,  442,  450,  441,
        0,  435,  443,    0,    0,    0,  456,  445,  448,  432,
      436,  434,  428,  430,  440,  429,  684,  432,  444,  428,
      422,  421,  420,  421,  166,  433,  419,  431,  442,  446,
      424,  417,    0,  415,    0,  417,  434,  412,  404,  410,

      410,  408,  413,  401,  396,  398,  411,  409,  402,  394,
      416,  403,  404,  394,  402,  389,  388,  399,  396,  389,
      392,  398,  395,  394,  393,  384,  379,  389,  375,  386,
      373,  385,  380,  377,  382,  385,  371,  383,  378,  378,
      367,  380,  379,  378,  368,    0,    0,  380,    0,  370,
      373,  355,  381,  367,  367,    0,   81,    0,    0,  364,
      378,  355,  365,    0,    0,    0,  364,  350,  347,  345,
      167,  344,  340,  348,    0,  341,  348,    0,  344,  684,
      350,  350,  336,  337,  369,  332,  340,    0,  330,  346,
      345,  345,  343,  326,  326,    0,  340,  335,  322,  329,

      334,  319,  169,  319,  329,  338,  327,  326,    0,  317,
      324,  178,  323,  309,  310,  325,  315,  311,  305,  303,
      308,  317,  300,  306,  316,  293,    0,  309,  300,    0,
      303,  295,  305,  295,  292,  298,  295,    0,    0,    0,
      294,  290,  325,  301,  287,  324,  285,  293,    0,  280,
      291,  284,  280,  279,  156,    0,  684,  684,  278,  277,
      274,  286,  271,  263,    0,  275,  272,  316,  265,  276,
      305,  267,    0,    0,  262,  277,  261,  258,  271,  153,
      251,  260,  269,  254,    0,  261,  264,  268,  262,  170,
      249,  265,    0,    0,  261,  263,  245,    0,  256,  259,

      244,    0,    0,  249,  243,    0,  256,  255,  253,  235,
      252,  193,  241,  241,  249,  245,  229,  241,  231,  231,
        0,  243,  224,  233,  194,  240,  239,  238,  233,  230,
        0,  216,  256,  220,    0,    0,  229,  226,  230,  229,
      252,  251,  209,    0,  209,  207,  255,    0,  214,  205,
      244,  243,  242,  241,  195,  210,  236,  174,  245,  244,
      235,  234,  200,  203,  239,  192,  200,  684,  684,  186,
        0,  174,  191,  185,  195,  181,  177,  175,  169,  180,
      166,  218,  166,  174,    0,  169,  684,  163,  145,  171,
      132,  110,  684,  108,  101,  684,  684,  684,  233,  236,

       88,  239
    } ;

static yyconst flex_int16_t yy_def[603] =
    {   0,
      598,    1,  598,  598,  598,  598,  599,  600,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  598,  598,  598,  599,  600,  600,
      598,  598,  598,  598,  602,  598,  598,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,

      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  599,  598,  598,  598,
      598,  598,  602,  602,  598,  598,  598,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  598,
      598,  598,  598,  598,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  598,  601,  601,

      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  598,  598,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      598,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  598,  601,  601,  598,
      601,  601,  601,  598,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  598,  601,  601,

      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  598,  601,  601,  601,  598,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  601,  598,  601,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  598,  601,  601,  601,  598,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  598,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  601,  598,  598,

      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  598,  598,  601,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  598,  598,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  598,  601,  601,
      598,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  598,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,

      601,  601,  601,  601,  601,  601,  601,  601,  598,  598,
      601,  601,  601,  601,  601,  601,  601,  601,  601,  601,
      601,  601,  598,  598,  601,  601,  601,  601,  601,  601,
      601,  601,  601,  601,  601,  601,  598,  598,  601,  601,
      601,  601,  601,  601,  601,  601,  598,  601,  598,  598,
      601,  601,  598,  598,  601,  601,  601,  598,  598,  598,
      598,  598,  601,  601,  598,  598,  598,  598,  598,  601,
      601,  598,  598,  598,  601,  598,  598,  598,  598,  601,
      598,  598,  598,  598,  601,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,    0,  598,  598,

      598,  598
    } ;

static yyconst flex_uint16_t yy_nxt[750] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   21,   25,   21,   26,   21,   21,   27,   28,
       29,   30,   31,   32,   33,   34,   21,   35,   36,   37,
       38,   39,   40,   41,   21,   42,   43,   21,   44,   21,
       21,   21,   45,   46,   47,   48,   49,   50,   21,   21,
       51,   52,   53,   54,    4,   55,   55,   55,   55,   55,
       63,   55,   64,   66,   70,   57,   76,   56,   56,   57,
       57,   56,   67,   57,   77,   78,   79,   71,   82,   89,
       68,  106,   91,  111,  109,  204,   92,  162,   99,  107,

      110,  112,  141,  142,   67,   93,   94,  205,  597,   90,
       83,  100,  163,  101,   55,  596,   55,  120,  102,  120,
      394,   66,  103,   57,   84,  120,   56,  120,   57,  171,
       67,  121,  150,  125,  395,  125,  104,  151,  122,  121,
      172,  152,  126,  120,  126,  120,  122,  127,  120,  184,
      120,  184,   67,  239,  595,  240,  181,  206,  181,  254,
      122,  277,  121,  127,  122,  182,  207,  182,  122,  122,
      183,  125,  255,  125,  278,  236,  594,  236,  593,  181,
      126,  181,  126,  257,  258,  127,  122,  592,  182,  183,
      182,  122,  184,  183,  184,  236,  441,  236,  327,  404,

      279,  432,  328,  405,  479,  433,  127,  499,  442,  183,
      500,  509,  480,  481,  526,  539,  566,  576,  527,  540,
      591,  590,  589,  510,  588,  587,  586,  585,  584,  583,
      567,  582,  577,   58,  581,   58,   59,  580,   59,  123,
      579,  123,  578,  575,  574,  573,  572,  571,  570,  562,
      561,  569,  568,  565,  564,  563,  554,  553,  562,  561,
      560,  559,  558,  557,  556,  555,  554,  553,  552,  551,
      550,  549,  548,  547,  546,  545,  544,  543,  542,  541,
      538,  537,  536,  535,  534,  533,  532,  531,  530,  529,
      528,  525,  524,  523,  522,  521,  520,  519,  518,  517,

      516,  515,  514,  513,  512,  511,  508,  507,  506,  505,
      504,  503,  502,  501,  498,  497,  496,  495,  494,  493,
      471,  492,  491,  490,  489,  488,  487,  486,  485,  484,
      483,  482,  478,  477,  476,  475,  474,  473,  472,  471,
      470,  469,  468,  467,  466,  465,  464,  463,  462,  461,
      460,  459,  458,  457,  456,  455,  454,  453,  452,  451,
      450,  449,  448,  447,  446,  445,  444,  443,  440,  439,
      438,  437,  436,  435,  434,  431,  430,  429,  428,  427,
      426,  425,  424,  423,  422,  421,  420,  419,  418,  417,
      416,  415,  414,  413,  412,  411,  410,  409,  408,  407,

      406,  403,  402,  401,  400,  399,  398,  397,  396,  393,
      392,  391,  390,  389,  388,  387,  386,  385,  384,  383,
      382,  381,  380,  379,  378,  377,  376,  375,  374,  373,
      372,  371,  370,  369,  368,  367,  366,  365,  364,  363,
      362,  361,  360,  359,  358,  357,  356,  355,  354,  353,
      352,  351,  350,  349,  348,  347,  346,  345,  344,  343,
      342,  341,  340,  339,  338,  337,  336,  335,  334,  333,
      332,  331,  330,  329,  326,  325,  324,  323,  322,  321,
      320,  319,  318,  317,  316,  315,  314,  313,  312,  311,
      310,  309,  308,  307,  306,  305,  304,  303,  302,  301,

      300,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  285,  284,  283,  282,  281,
      280,  276,  275,  274,  273,  272,  271,  270,  269,  268,
      267,  266,  265,  264,  263,  262,  261,  260,  259,  256,
      253,  252,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  238,  237,  183,  235,  234,  233,  232,
      231,  230,  229,  228,  227,  226,  225,  224,  223,  222,
      221,  220,  219,  218,  217,  216,  215,  214,  213,  212,
      211,  210,  209,  208,  203,  202,  201,  200,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  190,  189,  188,

      187,  186,  185,  127,  124,  180,  117,  179,  178,  177,
      176,  175,  174,  173,  170,  169,  168,  167,  166,  165,
      164,  161,  160,  159,  158,  157,  156,  155,  154,  153,
      149,  148,  147,  146,  145,  144,  143,  140,  139,  138,
      137,  136,  135,  134,  133,  132,  131,  130,  129,  128,
      124,   63,  119,  118,   60,  117,   64,  116,  115,  114,
      113,  108,  105,   98,   97,   96,   95,   88,   87,   86,
       85,   81,   80,   75,   74,   73,   72,   69,   65,   62,
       61,   60,  598,    3,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,

      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598
    } ;

static yyconst flex_int16_t yy_chk[750] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,   13,    5,   13,   15,
       16,   15,   16,   18,   23,   18,   28,    5,   13,    5,
       13,   15,   18,   15,   28,   29,   29,   23,   32,   39,
      601,   47,   40,   50,   49,  149,   40,  101,   45,   47,

       49,   50,   83,   83,   18,   40,   40,  149,  595,   39,
       32,   45,  101,   45,   55,  594,   55,   64,   45,   64,
      357,   57,   45,   57,   32,   66,   55,   66,   55,  109,
       57,   64,   91,   67,  357,   67,   45,   91,   64,   66,
      109,   91,   67,  120,   67,  120,   66,   67,  121,  126,
      121,  126,   57,  187,  592,  187,  122,  150,  122,  204,
       64,  230,  121,  126,  120,  122,  150,  122,   66,  121,
      122,  125,  204,  125,  230,  182,  591,  182,  590,  181,
      125,  181,  125,  206,  206,  125,  120,  589,  181,  182,
      181,  121,  184,  181,  184,  236,  412,  236,  285,  371,

      230,  403,  285,  371,  455,  403,  184,  480,  412,  236,
      480,  490,  455,  455,  512,  525,  558,  572,  512,  525,
      588,  586,  584,  490,  583,  582,  581,  580,  579,  578,
      558,  577,  572,  599,  576,  599,  600,  575,  600,  602,
      574,  602,  573,  570,  567,  566,  565,  564,  563,  562,
      561,  560,  559,  557,  556,  555,  554,  553,  552,  551,
      550,  549,  547,  546,  545,  543,  542,  541,  540,  539,
      538,  537,  534,  533,  532,  530,  529,  528,  527,  526,
      524,  523,  522,  520,  519,  518,  517,  516,  515,  514,
      513,  511,  510,  509,  508,  507,  505,  504,  501,  500,

      499,  497,  496,  495,  492,  491,  489,  488,  487,  486,
      484,  483,  482,  481,  479,  478,  477,  476,  475,  472,
      471,  470,  469,  468,  467,  466,  464,  463,  462,  461,
      460,  459,  454,  453,  452,  451,  450,  448,  447,  446,
      445,  444,  443,  442,  441,  437,  436,  435,  434,  433,
      432,  431,  429,  428,  426,  425,  424,  423,  422,  421,
      420,  419,  418,  417,  416,  415,  414,  413,  411,  410,
      408,  407,  406,  405,  404,  402,  401,  400,  399,  398,
      397,  395,  394,  393,  392,  391,  390,  389,  387,  386,
      385,  384,  383,  382,  381,  379,  377,  376,  374,  373,

      372,  370,  369,  368,  367,  363,  362,  361,  360,  355,
      354,  353,  352,  351,  350,  348,  345,  344,  343,  342,
      341,  340,  339,  338,  337,  336,  335,  334,  333,  332,
      331,  330,  329,  328,  327,  326,  325,  324,  323,  322,
      321,  320,  319,  318,  317,  316,  315,  314,  313,  312,
      311,  310,  309,  308,  307,  306,  305,  304,  303,  302,
      301,  300,  299,  298,  297,  296,  294,  292,  291,  290,
      289,  288,  287,  286,  284,  283,  282,  281,  280,  279,
      278,  276,  275,  274,  273,  272,  271,  270,  269,  268,
      267,  263,  262,  260,  259,  258,  257,  256,  255,  254,

      253,  252,  251,  250,  249,  248,  247,  246,  245,  244,
      242,  241,  240,  239,  238,  237,  235,  234,  233,  232,
      231,  229,  227,  226,  225,  224,  223,  221,  220,  219,
      216,  215,  214,  213,  212,  211,  210,  209,  207,  205,
      202,  201,  198,  197,  196,  195,  194,  193,  192,  191,
      190,  189,  188,  186,  185,  183,  180,  179,  178,  177,
      176,  175,  174,  173,  172,  171,  169,  168,  167,  166,
      165,  164,  163,  162,  161,  160,  159,  158,  157,  156,
      154,  153,  152,  151,  148,  147,  146,  145,  144,  143,
      142,  141,  140,  139,  137,  136,  135,  133,  132,  131,

      130,  129,  128,  127,  124,  118,  117,  116,  115,  114,
      113,  112,  111,  110,  108,  107,  106,  105,  104,  103,
      102,  100,   99,   98,   97,   96,   95,   94,   93,   92,
       90,   89,   88,   87,   86,   85,   84,   82,   81,   80,
       79,   78,   77,   76,   75,   74,   73,   71,   70,   69,
       65,   63,   62,   61,   60,   58,   56,   54,   53,   52,
       51,   48,   46,   44,   43,   42,   41,   38,   37,   34,
       33,   31,   30,   27,   26,   25,   24,   22,   17,   10,
        9,    8,    3,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,

      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[99] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
#line 2 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
#include <stdio.h>
#include <stdlib.h>

#include <BLProfParser.tab.H>

#define YY_NEVER_INTERACTIVE 1
#define ECHO return (0);       /* for unmatched tokens */

#line 871 "BLProfParser.lex.yy.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 136 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"



#line 1093 "BLProfParser.lex.yy.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 599 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 684 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case YY_STATE_EOF(INITIAL):
#line 139 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ /* stop here <<EOF>> */ BEGIN(INITIAL); return(ENDOFFILE); }
	YY_BREAK

 /* INITIAL */


case 1:
YY_RULE_SETUP
#line 146 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ /* ignore whitespace */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 147 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(MPITOKEN);   }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 148 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(OMP);   }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 149 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(COMMENT);   }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 150 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(DT);   }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 152 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(BLPROFVERSION);   }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 153 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(PHFNAME);   }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 154 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(BLPROFPROC);   }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 155 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ yylval.cValue = strdup(yytext); return(BLPROFDATAFILENAME); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 156 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(CALCENDTIME);   }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 158 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(COMMPROFVERSION);   }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 159 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(NPROCS);   }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 160 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(COMMSTATSSIZE);   }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 161 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(NOUTFILES);   }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 162 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(FINESTLEVEL);   }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 163 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(MAXLEVEL);   }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 164 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(REFRATIO);   }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 165 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(PROBDOMAIN);   }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 166 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(COMPUTE);   }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 167 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(SERVICE);   }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 168 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(HEADERFILE);   }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 169 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(CPDATAPROC);   }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 170 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(NCOMMSTATS);   }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 171 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(DATAFILE);   }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 172 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(SEEKPOS);   }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 173 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(BARRIERNUMBER);   }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 174 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(NAMETAG);   }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 175 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(NAMETAGNAMES);   }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 176 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(REDUCTION);   }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 177 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(TIMEMINMAX);   }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 178 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(TIMERTIME);   }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 179 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(TAGRANGE);   }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 180 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(NAME);   }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 181 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(INDEX);   }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 182 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(LPAREN);   }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 183 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(RPAREN);   }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 184 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ yylval.cValue = strdup(yytext); return(QNAME);   }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 185 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ yylval.cValue = strdup(yytext); return(COMMDATAFILENAME);   }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 186 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ yylval.cValue = strdup(yytext); return(COMMHEADERFILENAME);   }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 188 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(CALLSTATSPROFVERSION);   }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 189 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(FNAME);   }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 190 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(REGIONNAME);   }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 191 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(CALLSTATSPROC);   }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 192 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(NRSS);   }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 193 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(NTRACESTATS);   }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 194 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(INCLUDEALL);   }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 195 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(INCLUDENONE);   }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 196 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ yylval.cValue = strdup(yytext); return(CSTATSDATAFILENAME);   }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 197 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ yylval.cValue = strdup(yytext); return(CSTATSHEADERFILENAME);   }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 199 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ yylval.iValue = atol(yytext); return(NUMINTEGER); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 200 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ yylval.fValue = atof(yytext); return(NUMFLOAT);   }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 201 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ yylval.fValue = atof(yytext); return(NUMFLOAT);   }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 204 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(STEP);   }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 205 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(TIMEGL); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 206 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(REGRID); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 207 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(WLB);    }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 208 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(LEVEL);  }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 209 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(GRIDS);  }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 210 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(CELLS);  }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 211 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(PCTOD);  }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 214 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return RUNTIME; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 216 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(TIME);   }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 218 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(POUNDCOMMENT);   }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 219 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(CPU);  }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 220 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(SLOT); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 221 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(CAGE); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 222 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(CABINET); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 223 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(CAB_POSITION); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 224 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(CAB_ROW); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 225 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(X_COORD); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 226 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(Y_COORD); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 227 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(Z_COORD); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 228 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(PROCESS_SLOTS); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 229 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(PROCESS_SLOTS_FREE); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 230 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(PROCESSOR_STATUS_UP); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 231 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(PROCESSOR_STATUS_DOWN); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 232 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(PROCESSOR_TYPE_SERVICE); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 233 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(PROCESSOR_TYPE_COMPUTE); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 234 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(ALLOC_MODE_BATCH); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 235 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(ALLOC_MODE_OTHER); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 236 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(PROCESSOR_ID); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 237 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(OD_ALLOCATOR_ID); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 238 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(NEXT_RED_BLACK_SWITCH); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 239 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(PROCESSOR_SPEC); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 240 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return(SNULL); }
	YY_BREAK
case 86:
/* rule 86 can match eol */
YY_RULE_SETUP
#line 242 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return DELENDLINE; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 243 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return PLUS;       }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 244 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return MINUS;      }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 245 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return EQUAL; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 246 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return COLON; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 247 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return LBRACKET; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 248 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return RBRACKET; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 249 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return COMMA; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 251 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ yylval.cValue = strdup(yytext);  return(WORD);   }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 252 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ /* stop here EOS */       BEGIN(INITIAL); return(ENDOFFILE);  }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 253 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ return DOTS; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 254 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
{ /* yylval.cValue = strdup(yytext); */  return UNKNOWN; }
	YY_BREAK


 /* end INITIAL  */

case 98:
YY_RULE_SETUP
#line 263 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"
ECHO;
	YY_BREAK
#line 1663 "BLProfParser.lex.yy.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 65);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 599 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 65;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 599 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 598);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 263 "../../../../amrex/Src/Extern/ProfParser/BLProfParser.l"




/* need this because we cannot directly access elements of YY_BUFFER_STATE externally */
char *GetYYBufPos(YY_BUFFER_STATE ybs) {
  return ybs->yy_buf_pos;
}


