#!/bin/bash

range=6
ntest=100
interval=$(awk "BEGIN{interval=$range/$ntest;print interval}")
start=11
n=1
while [ $n -lt $ntest ]
do
num=$(awk "BEGIN{num=$n*$interval;print num}")
omega=$(awk "BEGIN{omega=$start+$num;print omega}")
options="domega=$omega"
#mpirun -n 1 ./main3d.gnu.MPI.ex inputs_3d $options"e5"
mpirun -n 1 ./main3d.gnu.MPI.ex inputs_3d "domega="$omega"e5"
((n++))
done
