amrex::Vector<amrex::Real> compressible::Yk_lo;
amrex::Vector<amrex::Real> compressible::Yk_hi;
amrex::Vector<amrex::Real> compressible::Xk_lo;
amrex::Vector<amrex::Real> compressible::Xk_hi;

// amrex::Vector<amrex::Real> compressible::Yk_lo_x;
// amrex::Vector<amrex::Real> compressible::Yk_hi_x;
// amrex::Vector<amrex::Real> compressible::Yk_lo_y;
// amrex::Vector<amrex::Real> compressible::Yk_hi_y;
// amrex::Vector<amrex::Real> compressible::Yk_lo_z;
// amrex::Vector<amrex::Real> compressible::Yk_hi_z;
// amrex::Vector<amrex::Real> compressible::Xk_lo_x;
// amrex::Vector<amrex::Real> compressible::Xk_hi_x;
// amrex::Vector<amrex::Real> compressible::Xk_lo_y;
// amrex::Vector<amrex::Real> compressible::Xk_hi_y;
// amrex::Vector<amrex::Real> compressible::Xk_lo_z;
// amrex::Vector<amrex::Real> compressible::Xk_hi_z;
