#!/bin/bash

rm -r ../exec/immersedIons/particlePlots
mkdir ../exec/immersedIons/particlePlots

it=0

for f in ../exec/immersedIons/parplt*
do
	echo "Processing $f/ directory"

	python amrex_to_vtp.py "$f/" particle0

	cp -v "$f/particles.vtp" "../exec/immersedIons/particlePlots/par$it.vtp"

	it=$(($it+1))
done
