#!/bin/bash

rm -r ../exec/immersedParticles/particlePlots
mkdir ../exec/immersedParticles/particlePlots

it=0

for f in ../exec/immersedParticles/plt*
do
	echo "Processing $f/ directory"

	python amrex_to_vtp.py "$f/" particle0

	cp -v "$f/particles.vtp" "../exec/immersedParticles/particlePlots/par$it.vtp"

	it=$(($it+1))
done
