
# This file is automatically generated by setup.py
short_version = '3.0.1'
version = '3.0.1'
full_version = '3.0.1.dev-bf5e96b'
git_revision = 'bf5e96be18d2d4a0179aeb1e7867ddef7b13433e'
release = False

if not release:
    version = full_version
