#!/bin/bash

rm -r ./particlePlots
mkdir ./particlePlots

it=0

for f in ./parplt*
do
	echo "Processing $f/ directory"

	python amrex_to_vtp.py "$f/" particle0

	cp -v "$f/particles.vtp" "./particlePlots/par$it.vtp"

	it=$(($it+1))
done
