#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript.html

#SBATCH -N 2
#SBATCH -C gpu
#SBATCH --ntasks-per-node=4
#SBATCH --gpus-per-node=4
#SBATCH --cpus-per-task=16
#SBATCH -q regular
#SBATCH -J
#SBATCH -A
#SBATCH -t

executable=../main3d.gnu.MPI.CUDA.ex
inputs_file=inputs_GF_reactivesurface_3D

#run the application:
srun $executable $inputs_file >> scrout
