# -Wextra-semi: GCC < 10 does not have this.
# -Wunreachable-code: GCC no longer has this option.
# -Wno-c++17-extensions: Clang complains about nodiscard if the standard is not set to c++17.

name: linux

on: [push, pull_request]

jobs:

  # Clone and cache AMReX
  amrex:
    name: AMReX
    runs-on: ubuntu-20.04
    - name: Clone AMReX
      uses: actions/checkout@v2
    - name: Cache AMReX
      uses: actions/cache@v2
      key: amrex 




  # Build Tools/Plotfile
  multispec:
    name: Multispec 
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: .github/workflows/dependencies/dependencies.sh
    - name: Clone AMReX
      uses: actions/checkout@v2
      with: 
        repository: AMReX-Codes/amrex
    - name: Build & Install
      run: |
        amrex
        cd exec/multispec
        pwd
        echo $AMREX_HOME
        make -j2 DIM=2 TINY_PROFILE=FALSE
      env: 
        AMREX_HOME: $GITHUB_ACTION_PATH/amrex
  
 
