# -Wextra-semi: GCC < 10 does not have this.
# -Wunreachable-code: GCC no longer has this option.
# -Wno-c++17-extensions: Clang complains about nodiscard if the standard is not set to c++17.

name: linux

on: [push, pull_request]

jobs:

  # Build Tools/Plotfile
  multispec:
    name: Multispec 
    runs-on: ubuntu-20.04
#   needs: AMReX
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: .github/workflows/dependencies/dependencies.sh
#    - name: download artifact
#      uses: actions/download-artifact@v2
#      with:
#        name: amrex
#        path: amrex
#    - name: 'Echo download path'
#      run: echo ${{steps.download.outputs.download-path}}
    - name: Clone AMReX
      uses: actions/checkout@v2
      with: 
        repository: AMReX-Codes/amrex
        ref: development
        path: amrex
    - name: Build & Install
      run: |
        ls
        cd exec/multispec
        pwd
        echo $AMREX_HOME
        make -j2 DIM=2 TINY_PROFILE=FALSE
      env: 
        #AMREX_HOME: ${{steps.download.outputs.download-path}}
        AMREX_HOME: $GITHUB_WORKSPACE/amrex
  
  # Clone and cache AMReX
  #  amrex:
  #    name: AMReX
  #    runs-on: ubuntu-20.04
  #    steps:
  #    - name: check things
  #      run: |
  #        ls
  #        pwd
  #        echo $GITHUB_ACTION_PATH
  #    - name: check things
  #      run: |
  #        mkdir amrex
  #        cd amrex
  #        ls
  #        pwd
  #        echo $GITHUB_ACTION_PATH
  #    - name: Clone AMReX
  #      uses: actions/checkout@v2
  #      with: 
  #        repository: AMReX-Codes/amrex
  #        ref: development
  #        path: amrex
  #
  #
  #    - name: check things
  #      run: |
  #        cd ~
  #        ls
  #        pwd
  #        echo $GITHUB_ACTION_PATH
  #    - name: upload artifact
  #      uses: actions/upload-artifact@v2
  #      with:
  #        name: amrex
  #        path: amrex
  #        
  #          # - name: Cache AMReX
  #          #   uses: actions/cache@v2
  #          #   with:
  #          #     path: ~/amrex
  #          #     key: amrex 
 
