name: linux

on: [push, pull_request]

jobs:

  # Build Multispec
  multispec:
    name: Multispec 
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: .github/workflows/dependencies/dependencies.sh
    - name: Clone AMReX
      uses: actions/checkout@v2
      with: 
        repository: AMReX-Codes/amrex
        ref: development
        path: amrex
    - name: Build & Install
      run: |
        cd exec/multispec
        make -j2 V=1 DIM=2 TINY_PROFILE=FALSE 
        make -j2 V=1 DIM=3 TINY_PROFILE=FALSE 
      env: 
        AMREX_HOME: $(GITHUB_WORKSPACE)/amrex
  
